FROM python:3.9

WORKDIR /opt/app
RUN apt-get update && apt-get install -y avahi-discover libavahi-compat-libdnssd-dev net-tools
COPY source .

# comment these two lines out if not working (packages are in distro/packages folder, unzip them in the source folder)
RUN pip install -r requirements.txt

EXPOSE 2080
CMD ./ibrewui