#!/usr/bin/env python
# -*- coding: utf8 -*

from iBrewConsole import *

#------------------------------------------------------
# iBrew
#
# Interface to Smarter Appliances
#
# https://github.com/Tristan79/iBrew
#
# Copyright © 2020 Tristan
#
# Aye!
#------------------------------------------------------

#------------------------------------------------------
# MAIN
#------------------------------------------------------

iBrewConsole().run(sys.argv[1:])

